"""initial schema

Revision ID: 11d221220fb5
Revises: 
Create Date: 2026-07-30 21:51:47.941241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d221220fb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('passive_investments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('gain_loss_pct', sa.Float(), nullable=True),
    sa.Column('gain_loss_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_passive_investments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passive_investments'))
    )
    op.create_index('ix_passive_investments_user_id', 'passive_investments', ['user_id'], unique=False)
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('native_currency', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.Column('cash_amount', sa.Float(), nullable=True),
    sa.Column('fx_rate_to_chf', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolio_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_transactions'))
    )
    op.create_index('ix_portfolio_transactions_user_ticker_date', 'portfolio_transactions', ['user_id', 'ticker', 'date'], unique=False)
    op.create_table('ticker_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('native_currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticker_metadata_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticker_metadata')),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_ticker_metadata_user_id_ticker')
    )
    op.create_table('passive_recurring_deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passive_investment_id', sa.Integer(), nullable=False),
    sa.Column('amount_native', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('last_generated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['passive_investment_id'], ['passive_investments.id'], name=op.f('fk_passive_recurring_deposits_passive_investment_id_passive_investments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passive_recurring_deposits')),
    sa.UniqueConstraint('passive_investment_id', name=op.f('uq_passive_recurring_deposits_passive_investment_id'))
    )
    op.create_table('passive_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passive_investment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_native', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['passive_investment_id'], ['passive_investments.id'], name=op.f('fk_passive_transactions_passive_investment_id_passive_investments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passive_transactions'))
    )
    op.create_index('ix_passive_transactions_investment_date', 'passive_transactions', ['passive_investment_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_passive_transactions_investment_date', table_name='passive_transactions')
    op.drop_table('passive_transactions')
    op.drop_table('passive_recurring_deposits')
    op.drop_table('ticker_metadata')
    op.drop_index('ix_portfolio_transactions_user_ticker_date', table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index('ix_passive_investments_user_id', table_name='passive_investments')
    op.drop_table('passive_investments')
    op.drop_table('users')
    # ### end Alembic commands ###
